<?php

/**
 * Implements theme_status_messages().
 */
function StatusMessages_status_messages($variables) {
  $display = $variables['display'];
  $output = '';

  $status_heading = array(
    'status' => t('Status message'),
    'error' => t('Error message'),
    'warning' => t('Warning message'),
  );
  foreach (drupal_get_messages($display) as $type => $messages) {
    $output .= '<div class="StatusMessages StatusMessages--' . $type . '">';
    $output .= '<div class="StatusMessages-inner">';
    if (!empty($status_heading[$type])) {
      $output .= '<h2 class="u-hiddenVisually">' . $status_heading[$type] . "</h2>\n";
    }
    if (count($messages) > 1) {
      $output .= " <ol>\n";
      foreach ($messages as $message) {
        $output .= '  <li>' . $message . "</li>\n";
      }
      $output .= " </ol>\n";
    }
    else {
      $output .= $messages[0];
    }
    $output .= "</div></div>\n";
  }
  return $output;
}
